# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FbsPostingShipV4RequestWith(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'additional_data': 'bool'
    }

    attribute_map = {
        'additional_data': 'additional_data'
    }

    def __init__(self, additional_data=None):  # noqa: E501
        """FbsPostingShipV4RequestWith - a model defined in Swagger"""  # noqa: E501
        self._additional_data = None
        self.discriminator = None
        if additional_data is not None:
            self.additional_data = additional_data

    @property
    def additional_data(self):
        """Gets the additional_data of this FbsPostingShipV4RequestWith.  # noqa: E501

        Чтобы получить дополнительную информацию, передайте `true`.  # noqa: E501

        :return: The additional_data of this FbsPostingShipV4RequestWith.  # noqa: E501
        :rtype: bool
        """
        return self._additional_data

    @additional_data.setter
    def additional_data(self, additional_data):
        """Sets the additional_data of this FbsPostingShipV4RequestWith.

        Чтобы получить дополнительную информацию, передайте `true`.  # noqa: E501

        :param additional_data: The additional_data of this FbsPostingShipV4RequestWith.  # noqa: E501
        :type: bool
        """

        self._additional_data = additional_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FbsPostingShipV4RequestWith, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FbsPostingShipV4RequestWith):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
