# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetProductInfoListResponseStocks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'has_stock': 'bool',
        'stocks': 'list[GetProductInfoListResponseStocksStock]'
    }

    attribute_map = {
        'has_stock': 'has_stock',
        'stocks': 'stocks'
    }

    def __init__(self, has_stock=None, stocks=None):  # noqa: E501
        """GetProductInfoListResponseStocks - a model defined in Swagger"""  # noqa: E501
        self._has_stock = None
        self._stocks = None
        self.discriminator = None
        if has_stock is not None:
            self.has_stock = has_stock
        if stocks is not None:
            self.stocks = stocks

    @property
    def has_stock(self):
        """Gets the has_stock of this GetProductInfoListResponseStocks.  # noqa: E501

        `true`, если есть остаток на складах.   # noqa: E501

        :return: The has_stock of this GetProductInfoListResponseStocks.  # noqa: E501
        :rtype: bool
        """
        return self._has_stock

    @has_stock.setter
    def has_stock(self, has_stock):
        """Sets the has_stock of this GetProductInfoListResponseStocks.

        `true`, если есть остаток на складах.   # noqa: E501

        :param has_stock: The has_stock of this GetProductInfoListResponseStocks.  # noqa: E501
        :type: bool
        """

        self._has_stock = has_stock

    @property
    def stocks(self):
        """Gets the stocks of this GetProductInfoListResponseStocks.  # noqa: E501

        Статус остатков товара.  # noqa: E501

        :return: The stocks of this GetProductInfoListResponseStocks.  # noqa: E501
        :rtype: list[GetProductInfoListResponseStocksStock]
        """
        return self._stocks

    @stocks.setter
    def stocks(self, stocks):
        """Sets the stocks of this GetProductInfoListResponseStocks.

        Статус остатков товара.  # noqa: E501

        :param stocks: The stocks of this GetProductInfoListResponseStocks.  # noqa: E501
        :type: list[GetProductInfoListResponseStocksStock]
        """

        self._stocks = stocks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetProductInfoListResponseStocks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetProductInfoListResponseStocks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
