# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetReturnsListResponseVisualStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'display_name': 'str',
        'sys_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'display_name': 'display_name',
        'sys_name': 'sys_name'
    }

    def __init__(self, id=None, display_name=None, sys_name=None):  # noqa: E501
        """GetReturnsListResponseVisualStatus - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._display_name = None
        self._sys_name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if display_name is not None:
            self.display_name = display_name
        if sys_name is not None:
            self.sys_name = sys_name

    @property
    def id(self):
        """Gets the id of this GetReturnsListResponseVisualStatus.  # noqa: E501

        Идентификатор статуса возврата.  # noqa: E501

        :return: The id of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetReturnsListResponseVisualStatus.

        Идентификатор статуса возврата.  # noqa: E501

        :param id: The id of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def display_name(self):
        """Gets the display_name of this GetReturnsListResponseVisualStatus.  # noqa: E501

        Название статуса возврата.  # noqa: E501

        :return: The display_name of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this GetReturnsListResponseVisualStatus.

        Название статуса возврата.  # noqa: E501

        :param display_name: The display_name of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def sys_name(self):
        """Gets the sys_name of this GetReturnsListResponseVisualStatus.  # noqa: E501

        Системное название статуса возврата.  # noqa: E501

        :return: The sys_name of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :rtype: str
        """
        return self._sys_name

    @sys_name.setter
    def sys_name(self, sys_name):
        """Sets the sys_name of this GetReturnsListResponseVisualStatus.

        Системное название статуса возврата.  # noqa: E501

        :param sys_name: The sys_name of this GetReturnsListResponseVisualStatus.  # noqa: E501
        :type: str
        """

        self._sys_name = sys_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetReturnsListResponseVisualStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetReturnsListResponseVisualStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
