# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PostingGetFboPostingRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'posting_number': 'str',
        'translit': 'bool',
        '_with': 'PostingFboPostingWithParams'
    }

    attribute_map = {
        'posting_number': 'posting_number',
        'translit': 'translit',
        '_with': 'with'
    }

    def __init__(self, posting_number=None, translit=None, _with=None):  # noqa: E501
        """PostingGetFboPostingRequest - a model defined in Swagger"""  # noqa: E501
        self._posting_number = None
        self._translit = None
        self.__with = None
        self.discriminator = None
        if posting_number is not None:
            self.posting_number = posting_number
        if translit is not None:
            self.translit = translit
        if _with is not None:
            self._with = _with

    @property
    def posting_number(self):
        """Gets the posting_number of this PostingGetFboPostingRequest.  # noqa: E501

        Номер отправления.  # noqa: E501

        :return: The posting_number of this PostingGetFboPostingRequest.  # noqa: E501
        :rtype: str
        """
        return self._posting_number

    @posting_number.setter
    def posting_number(self, posting_number):
        """Sets the posting_number of this PostingGetFboPostingRequest.

        Номер отправления.  # noqa: E501

        :param posting_number: The posting_number of this PostingGetFboPostingRequest.  # noqa: E501
        :type: str
        """

        self._posting_number = posting_number

    @property
    def translit(self):
        """Gets the translit of this PostingGetFboPostingRequest.  # noqa: E501

        Если включена транслитерация адреса из кириллицы в латиницу — `true`.  # noqa: E501

        :return: The translit of this PostingGetFboPostingRequest.  # noqa: E501
        :rtype: bool
        """
        return self._translit

    @translit.setter
    def translit(self, translit):
        """Sets the translit of this PostingGetFboPostingRequest.

        Если включена транслитерация адреса из кириллицы в латиницу — `true`.  # noqa: E501

        :param translit: The translit of this PostingGetFboPostingRequest.  # noqa: E501
        :type: bool
        """

        self._translit = translit

    @property
    def _with(self):
        """Gets the _with of this PostingGetFboPostingRequest.  # noqa: E501


        :return: The _with of this PostingGetFboPostingRequest.  # noqa: E501
        :rtype: PostingFboPostingWithParams
        """
        return self.__with

    @_with.setter
    def _with(self, _with):
        """Sets the _with of this PostingGetFboPostingRequest.


        :param _with: The _with of this PostingGetFboPostingRequest.  # noqa: E501
        :type: PostingFboPostingWithParams
        """

        self.__with = _with

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostingGetFboPostingRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostingGetFboPostingRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
