# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SellerApiProductPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_id': 'float',
        'action_price': 'float',
        'stock': 'float'
    }

    attribute_map = {
        'product_id': 'product_id',
        'action_price': 'action_price',
        'stock': 'stock'
    }

    def __init__(self, product_id=None, action_price=None, stock=None):  # noqa: E501
        """SellerApiProductPrice - a model defined in Swagger"""  # noqa: E501
        self._product_id = None
        self._action_price = None
        self._stock = None
        self.discriminator = None
        if product_id is not None:
            self.product_id = product_id
        if action_price is not None:
            self.action_price = action_price
        if stock is not None:
            self.stock = stock

    @property
    def product_id(self):
        """Gets the product_id of this SellerApiProductPrice.  # noqa: E501

        Идентификатор товара.  # noqa: E501

        :return: The product_id of this SellerApiProductPrice.  # noqa: E501
        :rtype: float
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this SellerApiProductPrice.

        Идентификатор товара.  # noqa: E501

        :param product_id: The product_id of this SellerApiProductPrice.  # noqa: E501
        :type: float
        """

        self._product_id = product_id

    @property
    def action_price(self):
        """Gets the action_price of this SellerApiProductPrice.  # noqa: E501

        Цена товара по акции.  # noqa: E501

        :return: The action_price of this SellerApiProductPrice.  # noqa: E501
        :rtype: float
        """
        return self._action_price

    @action_price.setter
    def action_price(self, action_price):
        """Sets the action_price of this SellerApiProductPrice.

        Цена товара по акции.  # noqa: E501

        :param action_price: The action_price of this SellerApiProductPrice.  # noqa: E501
        :type: float
        """

        self._action_price = action_price

    @property
    def stock(self):
        """Gets the stock of this SellerApiProductPrice.  # noqa: E501

        Количество единиц товара в акции типа «Скидка на сток».  # noqa: E501

        :return: The stock of this SellerApiProductPrice.  # noqa: E501
        :rtype: float
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this SellerApiProductPrice.

        Количество единиц товара в акции типа «Скидка на сток».  # noqa: E501

        :param stock: The stock of this SellerApiProductPrice.  # noqa: E501
        :type: float
        """

        self._stock = stock

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SellerApiProductPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SellerApiProductPrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
