# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1ProductCertificateInfoRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'certificate_number': 'str'
    }

    attribute_map = {
        'certificate_number': 'certificate_number'
    }

    def __init__(self, certificate_number=None):  # noqa: E501
        """V1ProductCertificateInfoRequest - a model defined in Swagger"""  # noqa: E501
        self._certificate_number = None
        self.discriminator = None
        self.certificate_number = certificate_number

    @property
    def certificate_number(self):
        """Gets the certificate_number of this V1ProductCertificateInfoRequest.  # noqa: E501

        Идентификатор сертификата.  # noqa: E501

        :return: The certificate_number of this V1ProductCertificateInfoRequest.  # noqa: E501
        :rtype: str
        """
        return self._certificate_number

    @certificate_number.setter
    def certificate_number(self, certificate_number):
        """Sets the certificate_number of this V1ProductCertificateInfoRequest.

        Идентификатор сертификата.  # noqa: E501

        :param certificate_number: The certificate_number of this V1ProductCertificateInfoRequest.  # noqa: E501
        :type: str
        """
        if certificate_number is None:
            raise ValueError("Invalid value for `certificate_number`, must not be `None`")  # noqa: E501

        self._certificate_number = certificate_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ProductCertificateInfoRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ProductCertificateInfoRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
