# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2Warehouse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'name': 'str',
        'warehouse_id': 'int'
    }

    attribute_map = {
        'address': 'address',
        'name': 'name',
        'warehouse_id': 'warehouse_id'
    }

    def __init__(self, address=None, name=None, warehouse_id=None):  # noqa: E501
        """V2Warehouse - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._name = None
        self._warehouse_id = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if name is not None:
            self.name = name
        if warehouse_id is not None:
            self.warehouse_id = warehouse_id

    @property
    def address(self):
        """Gets the address of this V2Warehouse.  # noqa: E501

        Адрес склада.  # noqa: E501

        :return: The address of this V2Warehouse.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this V2Warehouse.

        Адрес склада.  # noqa: E501

        :param address: The address of this V2Warehouse.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def name(self):
        """Gets the name of this V2Warehouse.  # noqa: E501

        Название склада.  # noqa: E501

        :return: The name of this V2Warehouse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2Warehouse.

        Название склада.  # noqa: E501

        :param name: The name of this V2Warehouse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def warehouse_id(self):
        """Gets the warehouse_id of this V2Warehouse.  # noqa: E501

        Идентификатор склада.  # noqa: E501

        :return: The warehouse_id of this V2Warehouse.  # noqa: E501
        :rtype: int
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """Sets the warehouse_id of this V2Warehouse.

        Идентификатор склада.  # noqa: E501

        :param warehouse_id: The warehouse_id of this V2Warehouse.  # noqa: E501
        :type: int
        """

        self._warehouse_id = warehouse_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2Warehouse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2Warehouse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
