# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.0.73

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.billing_create_new_service_order_v1422_response_errors import BillingCreateNewServiceOrderV1422ResponseErrors

class TestBillingCreateNewServiceOrderV1422ResponseErrors(unittest.TestCase):
    """BillingCreateNewServiceOrderV1422ResponseErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingCreateNewServiceOrderV1422ResponseErrors:
        """Test BillingCreateNewServiceOrderV1422ResponseErrors
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingCreateNewServiceOrderV1422ResponseErrors`
        """
        model = BillingCreateNewServiceOrderV1422ResponseErrors()
        if include_optional:
            return BillingCreateNewServiceOrderV1422ResponseErrors(
                field_1 = ["The field_1 field is required.","The field_1 must be a number."],
                field_2 = ["The field_2 field is required.","The field_2 must be a string."]
            )
        else:
            return BillingCreateNewServiceOrderV1422ResponseErrors(
        )
        """

    def testBillingCreateNewServiceOrderV1422ResponseErrors(self):
        """Test BillingCreateNewServiceOrderV1422ResponseErrors"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
