from amsdal.models.core.class_property_meta import *
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from typing import Any, ClassVar

class ClassObjectMeta(Model):
    __module_type__: ClassVar[ModuleType] = ...
    title: str = ...
    type: str = ...
    default: Any | None = ...
    class_schema_type: str | None = ...
    properties: dict[str, ClassPropertyMeta | None] | None = ...
    custom_code: str | None = ...
    @classmethod
    def _non_empty_keys_properties(cls, value: Any) -> Any: ...
