# Generated by Django 4.2.21 on 2025-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_site_warnings", "0006_auto_20231025_1637"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warning",
            name="auto_reset_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="current_step",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="done_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="status",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="step1_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="step2_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="step3_time",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="success",
        ),
        migrations.AlterField(
            model_name="warning",
            name="add_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Add Time"),
        ),
        migrations.AlterField(
            model_name="warning",
            name="mod_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Modify Time"
            ),
        ),
    ]
