"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stepintegrationissueenum import StepIntegrationIssueEnum
from novu_py.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StepIntegrationIssueTypedDict(TypedDict):
    issue_type: StepIntegrationIssueEnum
    r"""Type of integration issue"""
    message: str
    r"""Detailed message describing the issue"""
    variable_name: NotRequired[str]
    r"""Name of the variable related to the issue"""


class StepIntegrationIssue(BaseModel):
    issue_type: Annotated[StepIntegrationIssueEnum, pydantic.Field(alias="issueType")]
    r"""Type of integration issue"""

    message: str
    r"""Detailed message describing the issue"""

    variable_name: Annotated[Optional[str], pydantic.Field(alias="variableName")] = None
    r"""Name of the variable related to the issue"""
