
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-20T16:23:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e02970806ab54b17d2218a21cb5efb14cc99ecc4",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
