// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xla/backends/cpu/xnnpack_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto PROTOBUF_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct PROTOBUF_EXPORT TableStruct_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto {
  static const uint32_t offsets[];
};
PROTOBUF_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto;
namespace xla {
namespace cpu {
class XnnFusionBackendConfig;
struct XnnFusionBackendConfigDefaultTypeInternal;
PROTOBUF_EXPORT extern XnnFusionBackendConfigDefaultTypeInternal _XnnFusionBackendConfig_default_instance_;
}  // namespace cpu
}  // namespace xla
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_EXPORT ::xla::cpu::XnnFusionBackendConfig* Arena::CreateMaybeMessage<::xla::cpu::XnnFusionBackendConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xla {
namespace cpu {

// ===================================================================

class PROTOBUF_EXPORT XnnFusionBackendConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xla.cpu.XnnFusionBackendConfig) */ {
 public:
  inline XnnFusionBackendConfig() : XnnFusionBackendConfig(nullptr) {}
  ~XnnFusionBackendConfig() override;
  explicit PROTOBUF_CONSTEXPR XnnFusionBackendConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XnnFusionBackendConfig(const XnnFusionBackendConfig& from);
  XnnFusionBackendConfig(XnnFusionBackendConfig&& from) noexcept
    : XnnFusionBackendConfig() {
    *this = ::std::move(from);
  }

  inline XnnFusionBackendConfig& operator=(const XnnFusionBackendConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline XnnFusionBackendConfig& operator=(XnnFusionBackendConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XnnFusionBackendConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const XnnFusionBackendConfig* internal_default_instance() {
    return reinterpret_cast<const XnnFusionBackendConfig*>(
               &_XnnFusionBackendConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(XnnFusionBackendConfig& a, XnnFusionBackendConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(XnnFusionBackendConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XnnFusionBackendConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XnnFusionBackendConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XnnFusionBackendConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XnnFusionBackendConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XnnFusionBackendConfig& from) {
    XnnFusionBackendConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XnnFusionBackendConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xla.cpu.XnnFusionBackendConfig";
  }
  protected:
  explicit XnnFusionBackendConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUseThreadpoolFieldNumber = 1,
  };
  // bool use_threadpool = 1;
  void clear_use_threadpool();
  bool use_threadpool() const;
  void set_use_threadpool(bool value);
  private:
  bool _internal_use_threadpool() const;
  void _internal_set_use_threadpool(bool value);
  public:

  // @@protoc_insertion_point(class_scope:xla.cpu.XnnFusionBackendConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool use_threadpool_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XnnFusionBackendConfig

// bool use_threadpool = 1;
inline void XnnFusionBackendConfig::clear_use_threadpool() {
  _impl_.use_threadpool_ = false;
}
inline bool XnnFusionBackendConfig::_internal_use_threadpool() const {
  return _impl_.use_threadpool_;
}
inline bool XnnFusionBackendConfig::use_threadpool() const {
  // @@protoc_insertion_point(field_get:xla.cpu.XnnFusionBackendConfig.use_threadpool)
  return _internal_use_threadpool();
}
inline void XnnFusionBackendConfig::_internal_set_use_threadpool(bool value) {
  
  _impl_.use_threadpool_ = value;
}
inline void XnnFusionBackendConfig::set_use_threadpool(bool value) {
  _internal_set_use_threadpool(value);
  // @@protoc_insertion_point(field_set:xla.cpu.XnnFusionBackendConfig.use_threadpool)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cpu
}  // namespace xla

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xla_2fbackends_2fcpu_2fxnnpack_5fconfig_2eproto
