# This file was auto-generated by Fern from our API Definition.

from .......core.pydantic_utilities import UniversalBaseModel
import typing
from .iis_web_server_details import IisWebServerDetails
from .iis_web_framework_details import IisWebFrameworkDetails
import pydantic
from .......core.pydantic_utilities import IS_PYDANTIC_V2


class IisSiteDetails(UniversalBaseModel):
    server: typing.Optional[IisWebServerDetails] = None
    frameworks: typing.Optional[typing.List[IisWebFrameworkDetails]] = None
    authentication_methods: typing.Optional[typing.List[str]] = pydantic.Field(
        alias="authenticationMethods", default=None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
