# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PayoutChannel(str, Enum):
    """
    PayoutChannel defines the method by which settlement funds are paid out: - `Crypto`: Funds will be settled to a pre-approved blockchain crypto address. (Requires crypto_address_id to be specified.) - `OffRamp`: Funds will be settled through an off-ramp to a fiat bank account. (Requires bank_account_id to be specified.) 
    """

    """
    allowed enum values
    """
    CRYPTO = 'Crypto'
    OFFRAMP = 'OffRamp'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PayoutChannel from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


