"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from duckyai import utils
from duckyai.types import BaseModel
from typing import Optional


class ErrorResponseData(BaseModel):
    error: Optional[str] = None
    r"""Error message explaining the issue"""


class ErrorResponse(Exception):
    data: ErrorResponseData

    def __init__(self, data: ErrorResponseData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ErrorResponseData)
