# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CurrencyEnum(str, Enum):
    """
    CurrencyEnum
    """

    """
    allowed enum values
    """
    USD = 'usd'
    BRL = 'brl'
    EUR = 'eur'
    GBP = 'gbp'
    AUD = 'aud'
    CAD = 'cad'
    NOK = 'nok'
    SEK = 'sek'
    MXN = 'mxn'
    INR = 'inr'
    ARS = 'ars'
    COP = 'cop'
    CLP = 'clp'
    NZD = 'nzd'
    JPY = 'jpy'
    CHF = 'chf'
    CNY = 'cny'
    HKD = 'hkd'
    SGD = 'sgd'
    PLN = 'pln'
    DKK = 'dkk'
    ZAR = 'zar'
    THB = 'thb'
    MYR = 'myr'
    ILS = 'ils'
    PHP = 'php'
    TRY = 'try'
    IDR = 'idr'
    CZK = 'czk'
    AED = 'aed'
    SAR = 'sar'
    RUB = 'rub'
    ALL = 'all'
    AMD = 'amd'
    ANG = 'ang'
    AOA = 'aoa'
    AWG = 'awg'
    AZN = 'azn'
    BAM = 'bam'
    BBD = 'bbd'
    BDT = 'bdt'
    BGN = 'bgn'
    BIF = 'bif'
    BMD = 'bmd'
    BND = 'bnd'
    BOB = 'bob'
    BSD = 'bsd'
    BWP = 'bwp'
    BZD = 'bzd'
    CRC = 'crc'
    CVE = 'cve'
    DJF = 'djf'
    DOP = 'dop'
    DZD = 'dzd'
    EGP = 'egp'
    ETB = 'etb'
    FJD = 'fjd'
    FKP = 'fkp'
    GEL = 'gel'
    GIP = 'gip'
    GMD = 'gmd'
    GNF = 'gnf'
    GTQ = 'gtq'
    GYD = 'gyd'
    HNL = 'hnl'
    HUF = 'huf'
    JMD = 'jmd'
    KES = 'kes'
    KGS = 'kgs'
    KHR = 'khr'
    KMF = 'kmf'
    KRW = 'krw'
    KYD = 'kyd'
    KZT = 'kzt'
    LAK = 'lak'
    LBP = 'lbp'
    LKR = 'lkr'
    LRD = 'lrd'
    LSL = 'lsl'
    MAD = 'mad'
    MDL = 'mdl'
    MKD = 'mkd'
    MNT = 'mnt'
    MOP = 'mop'
    MUR = 'mur'
    MVR = 'mvr'
    MWK = 'mwk'
    NAD = 'nad'
    NGN = 'ngn'
    NIO = 'nio'
    NPR = 'npr'
    PAB = 'pab'
    PEN = 'pen'
    PGK = 'pgk'
    PKR = 'pkr'
    PYG = 'pyg'
    QAR = 'qar'
    RON = 'ron'
    RSD = 'rsd'
    RWF = 'rwf'
    SBD = 'sbd'
    SCR = 'scr'
    SHP = 'shp'
    SRD = 'srd'
    STD = 'std'
    SZL = 'szl'
    TJS = 'tjs'
    TOP = 'top'
    TTD = 'ttd'
    TWD = 'twd'
    TZS = 'tzs'
    UAH = 'uah'
    UGX = 'ugx'
    UYU = 'uyu'
    UZS = 'uzs'
    VND = 'vnd'
    VUV = 'vuv'
    WST = 'wst'
    XAF = 'xaf'
    XCD = 'xcd'
    XOF = 'xof'
    XPF = 'xpf'
    ZMW = 'zmw'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CurrencyEnum from a JSON string"""
        return cls(json.loads(json_str))


