# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RefundReasonEnum(str, Enum):
    """
    RefundReasonEnum
    """

    """
    allowed enum values
    """
    MANUAL = 'manual'
    DUPLICATE = 'duplicate'
    FRAUDULENT = 'fraudulent'
    REQUESTED_BY_CUSTOMER = 'requested_by_customer'
    EXPIRED_UNCAPTURED_CHARGE = 'expired_uncaptured_charge'
    MANUAL_OUT_OF_BAND = 'manual_out_of_band'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RefundReasonEnum from a JSON string"""
        return cls(json.loads(json_str))


