
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-19T06:02:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a66fb22607f37542ff406263140e94a2800919b8",
 "version": "1.33.1.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
