# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetProductRatingBySkuResponseProductRating(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sku': 'int',
        'rating': 'float',
        'groups': 'list[GetProductRatingBySkuResponseRatingGroup]'
    }

    attribute_map = {
        'sku': 'sku',
        'rating': 'rating',
        'groups': 'groups'
    }

    def __init__(self, sku=None, rating=None, groups=None):  # noqa: E501
        """GetProductRatingBySkuResponseProductRating - a model defined in Swagger"""  # noqa: E501
        self._sku = None
        self._rating = None
        self._groups = None
        self.discriminator = None
        if sku is not None:
            self.sku = sku
        if rating is not None:
            self.rating = rating
        if groups is not None:
            self.groups = groups

    @property
    def sku(self):
        """Gets the sku of this GetProductRatingBySkuResponseProductRating.  # noqa: E501

        Идентификатор товара на Ozon.  # noqa: E501

        :return: The sku of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :rtype: int
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this GetProductRatingBySkuResponseProductRating.

        Идентификатор товара на Ozon.  # noqa: E501

        :param sku: The sku of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :type: int
        """

        self._sku = sku

    @property
    def rating(self):
        """Gets the rating of this GetProductRatingBySkuResponseProductRating.  # noqa: E501

        Контент-рейтинг товара: от 0 до 100.   # noqa: E501

        :return: The rating of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :rtype: float
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this GetProductRatingBySkuResponseProductRating.

        Контент-рейтинг товара: от 0 до 100.   # noqa: E501

        :param rating: The rating of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :type: float
        """

        self._rating = rating

    @property
    def groups(self):
        """Gets the groups of this GetProductRatingBySkuResponseProductRating.  # noqa: E501

        Группы характеристик, из которых складывается контент-рейтинг.  # noqa: E501

        :return: The groups of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :rtype: list[GetProductRatingBySkuResponseRatingGroup]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this GetProductRatingBySkuResponseProductRating.

        Группы характеристик, из которых складывается контент-рейтинг.  # noqa: E501

        :param groups: The groups of this GetProductRatingBySkuResponseProductRating.  # noqa: E501
        :type: list[GetProductRatingBySkuResponseRatingGroup]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetProductRatingBySkuResponseProductRating, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetProductRatingBySkuResponseProductRating):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
