# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OperationPosting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delivery_schema': 'str',
        'order_date': 'str',
        'posting_number': 'str',
        'warehouse_id': 'int'
    }

    attribute_map = {
        'delivery_schema': 'delivery_schema',
        'order_date': 'order_date',
        'posting_number': 'posting_number',
        'warehouse_id': 'warehouse_id'
    }

    def __init__(self, delivery_schema=None, order_date=None, posting_number=None, warehouse_id=None):  # noqa: E501
        """OperationPosting - a model defined in Swagger"""  # noqa: E501
        self._delivery_schema = None
        self._order_date = None
        self._posting_number = None
        self._warehouse_id = None
        self.discriminator = None
        if delivery_schema is not None:
            self.delivery_schema = delivery_schema
        if order_date is not None:
            self.order_date = order_date
        if posting_number is not None:
            self.posting_number = posting_number
        if warehouse_id is not None:
            self.warehouse_id = warehouse_id

    @property
    def delivery_schema(self):
        """Gets the delivery_schema of this OperationPosting.  # noqa: E501

        Схема доставки:   - `FBO` — доставка со склада Ozon,   - `FBS` — доставка со своего склада,   - `RFBS` — доставка по выбору продавца,   - `Crossborder` — доставка из-за рубежа.   # noqa: E501

        :return: The delivery_schema of this OperationPosting.  # noqa: E501
        :rtype: str
        """
        return self._delivery_schema

    @delivery_schema.setter
    def delivery_schema(self, delivery_schema):
        """Sets the delivery_schema of this OperationPosting.

        Схема доставки:   - `FBO` — доставка со склада Ozon,   - `FBS` — доставка со своего склада,   - `RFBS` — доставка по выбору продавца,   - `Crossborder` — доставка из-за рубежа.   # noqa: E501

        :param delivery_schema: The delivery_schema of this OperationPosting.  # noqa: E501
        :type: str
        """

        self._delivery_schema = delivery_schema

    @property
    def order_date(self):
        """Gets the order_date of this OperationPosting.  # noqa: E501

        Дата принятия отправления в обработку.  # noqa: E501

        :return: The order_date of this OperationPosting.  # noqa: E501
        :rtype: str
        """
        return self._order_date

    @order_date.setter
    def order_date(self, order_date):
        """Sets the order_date of this OperationPosting.

        Дата принятия отправления в обработку.  # noqa: E501

        :param order_date: The order_date of this OperationPosting.  # noqa: E501
        :type: str
        """

        self._order_date = order_date

    @property
    def posting_number(self):
        """Gets the posting_number of this OperationPosting.  # noqa: E501

        Номер отправления.  # noqa: E501

        :return: The posting_number of this OperationPosting.  # noqa: E501
        :rtype: str
        """
        return self._posting_number

    @posting_number.setter
    def posting_number(self, posting_number):
        """Sets the posting_number of this OperationPosting.

        Номер отправления.  # noqa: E501

        :param posting_number: The posting_number of this OperationPosting.  # noqa: E501
        :type: str
        """

        self._posting_number = posting_number

    @property
    def warehouse_id(self):
        """Gets the warehouse_id of this OperationPosting.  # noqa: E501

        Идентификатор склада.  # noqa: E501

        :return: The warehouse_id of this OperationPosting.  # noqa: E501
        :rtype: int
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """Sets the warehouse_id of this OperationPosting.

        Идентификатор склада.  # noqa: E501

        :param warehouse_id: The warehouse_id of this OperationPosting.  # noqa: E501
        :type: int
        """

        self._warehouse_id = warehouse_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperationPosting, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperationPosting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
