# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuantsV1ListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cursor': 'str',
        'filter': 'QuantsV1ListRequestFilter',
        'limit': 'int',
        'sort': 'str',
        'sort_dir': 'str'
    }

    attribute_map = {
        'cursor': 'cursor',
        'filter': 'filter',
        'limit': 'limit',
        'sort': 'sort',
        'sort_dir': 'sort_dir'
    }

    def __init__(self, cursor=None, filter=None, limit=None, sort=None, sort_dir=None):  # noqa: E501
        """QuantsV1ListRequest - a model defined in Swagger"""  # noqa: E501
        self._cursor = None
        self._filter = None
        self._limit = None
        self._sort = None
        self._sort_dir = None
        self.discriminator = None
        if cursor is not None:
            self.cursor = cursor
        if filter is not None:
            self.filter = filter
        if limit is not None:
            self.limit = limit
        if sort is not None:
            self.sort = sort
        if sort_dir is not None:
            self.sort_dir = sort_dir

    @property
    def cursor(self):
        """Gets the cursor of this QuantsV1ListRequest.  # noqa: E501

        Указатель для выборки следующих данных.  # noqa: E501

        :return: The cursor of this QuantsV1ListRequest.  # noqa: E501
        :rtype: str
        """
        return self._cursor

    @cursor.setter
    def cursor(self, cursor):
        """Sets the cursor of this QuantsV1ListRequest.

        Указатель для выборки следующих данных.  # noqa: E501

        :param cursor: The cursor of this QuantsV1ListRequest.  # noqa: E501
        :type: str
        """

        self._cursor = cursor

    @property
    def filter(self):
        """Gets the filter of this QuantsV1ListRequest.  # noqa: E501


        :return: The filter of this QuantsV1ListRequest.  # noqa: E501
        :rtype: QuantsV1ListRequestFilter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this QuantsV1ListRequest.


        :param filter: The filter of this QuantsV1ListRequest.  # noqa: E501
        :type: QuantsV1ListRequestFilter
        """

        self._filter = filter

    @property
    def limit(self):
        """Gets the limit of this QuantsV1ListRequest.  # noqa: E501

        Максимальное количество значений в ответе.  # noqa: E501

        :return: The limit of this QuantsV1ListRequest.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this QuantsV1ListRequest.

        Максимальное количество значений в ответе.  # noqa: E501

        :param limit: The limit of this QuantsV1ListRequest.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def sort(self):
        """Gets the sort of this QuantsV1ListRequest.  # noqa: E501

        Параметр, по которому товары будут отсортированы.  # noqa: E501

        :return: The sort of this QuantsV1ListRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this QuantsV1ListRequest.

        Параметр, по которому товары будут отсортированы.  # noqa: E501

        :param sort: The sort of this QuantsV1ListRequest.  # noqa: E501
        :type: str
        """

        self._sort = sort

    @property
    def sort_dir(self):
        """Gets the sort_dir of this QuantsV1ListRequest.  # noqa: E501

        Направление сортировки: - `asc` — по возрастанию, - `desc` — по убыванию.   # noqa: E501

        :return: The sort_dir of this QuantsV1ListRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_dir

    @sort_dir.setter
    def sort_dir(self, sort_dir):
        """Sets the sort_dir of this QuantsV1ListRequest.

        Направление сортировки: - `asc` — по возрастанию, - `desc` — по убыванию.   # noqa: E501

        :param sort_dir: The sort_dir of this QuantsV1ListRequest.  # noqa: E501
        :type: str
        """

        self._sort_dir = sort_dir

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuantsV1ListRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuantsV1ListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
