# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RowItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'barcode': 'str',
        'name': 'str',
        'offer_id': 'str',
        'sku': 'int'
    }

    attribute_map = {
        'barcode': 'barcode',
        'name': 'name',
        'offer_id': 'offer_id',
        'sku': 'sku'
    }

    def __init__(self, barcode=None, name=None, offer_id=None, sku=None):  # noqa: E501
        """RowItem - a model defined in Swagger"""  # noqa: E501
        self._barcode = None
        self._name = None
        self._offer_id = None
        self._sku = None
        self.discriminator = None
        if barcode is not None:
            self.barcode = barcode
        if name is not None:
            self.name = name
        if offer_id is not None:
            self.offer_id = offer_id
        if sku is not None:
            self.sku = sku

    @property
    def barcode(self):
        """Gets the barcode of this RowItem.  # noqa: E501

        Штрихкод товара.  # noqa: E501

        :return: The barcode of this RowItem.  # noqa: E501
        :rtype: str
        """
        return self._barcode

    @barcode.setter
    def barcode(self, barcode):
        """Sets the barcode of this RowItem.

        Штрихкод товара.  # noqa: E501

        :param barcode: The barcode of this RowItem.  # noqa: E501
        :type: str
        """

        self._barcode = barcode

    @property
    def name(self):
        """Gets the name of this RowItem.  # noqa: E501

        Наименование товара.  # noqa: E501

        :return: The name of this RowItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RowItem.

        Наименование товара.  # noqa: E501

        :param name: The name of this RowItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def offer_id(self):
        """Gets the offer_id of this RowItem.  # noqa: E501

        Артикул товара.  # noqa: E501

        :return: The offer_id of this RowItem.  # noqa: E501
        :rtype: str
        """
        return self._offer_id

    @offer_id.setter
    def offer_id(self, offer_id):
        """Sets the offer_id of this RowItem.

        Артикул товара.  # noqa: E501

        :param offer_id: The offer_id of this RowItem.  # noqa: E501
        :type: str
        """

        self._offer_id = offer_id

    @property
    def sku(self):
        """Gets the sku of this RowItem.  # noqa: E501

        SKU товара.  # noqa: E501

        :return: The sku of this RowItem.  # noqa: E501
        :rtype: int
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this RowItem.

        SKU товара.  # noqa: E501

        :param sku: The sku of this RowItem.  # noqa: E501
        :type: int
        """

        self._sku = sku

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RowItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RowItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
