# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1BundleId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bundle_id': 'str',
        'is_docless': 'bool'
    }

    attribute_map = {
        'bundle_id': 'bundle_id',
        'is_docless': 'is_docless'
    }

    def __init__(self, bundle_id=None, is_docless=None):  # noqa: E501
        """V1BundleId - a model defined in Swagger"""  # noqa: E501
        self._bundle_id = None
        self._is_docless = None
        self.discriminator = None
        if bundle_id is not None:
            self.bundle_id = bundle_id
        if is_docless is not None:
            self.is_docless = is_docless

    @property
    def bundle_id(self):
        """Gets the bundle_id of this V1BundleId.  # noqa: E501

        Идентификатор комплекта. Используйте параметр в методе [/v1/supply-order/bundle](#operation/SupplyOrderBundle), чтобы получить подробную информацию.   # noqa: E501

        :return: The bundle_id of this V1BundleId.  # noqa: E501
        :rtype: str
        """
        return self._bundle_id

    @bundle_id.setter
    def bundle_id(self, bundle_id):
        """Sets the bundle_id of this V1BundleId.

        Идентификатор комплекта. Используйте параметр в методе [/v1/supply-order/bundle](#operation/SupplyOrderBundle), чтобы получить подробную информацию.   # noqa: E501

        :param bundle_id: The bundle_id of this V1BundleId.  # noqa: E501
        :type: str
        """

        self._bundle_id = bundle_id

    @property
    def is_docless(self):
        """Gets the is_docless of this V1BundleId.  # noqa: E501

        Признак необходимости передачи УПД: - `true` — документы не требуются, - `false` — требуются.   # noqa: E501

        :return: The is_docless of this V1BundleId.  # noqa: E501
        :rtype: bool
        """
        return self._is_docless

    @is_docless.setter
    def is_docless(self, is_docless):
        """Sets the is_docless of this V1BundleId.

        Признак необходимости передачи УПД: - `true` — документы не требуются, - `false` — требуются.   # noqa: E501

        :param is_docless: The is_docless of this V1BundleId.  # noqa: E501
        :type: bool
        """

        self._is_docless = is_docless

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1BundleId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1BundleId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
