# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
from .draft_labels import DraftLabels
from .draft_to import DraftTo
from .draft_cc import DraftCc
from .draft_bcc import DraftBcc
from .draft_subject import DraftSubject
from .draft_text import DraftText
from .draft_html import DraftHtml
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CreateDraftRequest(UncheckedBaseModel):
    labels: typing.Optional[DraftLabels] = None
    to: typing.Optional[DraftTo] = None
    cc: typing.Optional[DraftCc] = None
    bcc: typing.Optional[DraftBcc] = None
    subject: typing.Optional[DraftSubject] = None
    text: typing.Optional[DraftText] = None
    html: typing.Optional[DraftHtml] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
