from enum import Enum


class OrderStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    EXECUTED = "EXECUTED"
    CANCELLED = "CANCELLED"
    INDIVIDUAL_FILLS = "INDIVIDUAL_FILLS"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"
    PRE_SUBMISSION = "PRE_SUBMISSION"
    ANY = "ANY"
