# coding: utf-8

"""
    Devdraft Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.       # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import devdraft_ai_sdk
from devdraft_ai_sdk.models.update_webhook_dto import UpdateWebhookDto  # noqa: E501
from devdraft_ai_sdk.rest import ApiException


class TestUpdateWebhookDto(unittest.TestCase):
    """UpdateWebhookDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateWebhookDto(self):
        """Test UpdateWebhookDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = devdraft_ai_sdk.models.update_webhook_dto.UpdateWebhookDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
