
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-17T17:56:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "113b0272f639f1f5bb8da5e29d7763f87efa48ad",
 "version": "v0.38.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
