from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from typing import Any, ClassVar

class Object(Model):
    __module_type__: ClassVar[ModuleType] = ...
    title: str | None = ...
    type: str | None = ...
    default: Any | None = ...
    properties: dict[str, Any | None] | None = ...
    required: list[str] | None = ...
    unique: list[list[str]] | None = ...
    custom_code: str | None = ...
    meta_class: str | None = ...
    @classmethod
    def _non_empty_keys_properties(cls, value: Any) -> Any: ...
