# coding: utf-8

"""
    Ringer Business API - Phone Number Management

    This API provides endpoints for managing phone numbers within a Ringer Business account and its sites. Phone numbers are essential for making and receiving calls and can be routed to various features like devices, menus, or voicemail.  Functionality includes: - Listing phone numbers associated with a specific site. - Assigning (creating) a new phone number to a site. - Retrieving details of a specific phone number. - Updating a phone number's configuration (e.g., its routing destination). - Deleting/unassigning a phone number from a site. - Transferring a phone number between sites. - Listing available phone numbers for assignment to a site (from inventory or search). - Searching for available phone numbers based on criteria like area code, city, etc. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ringer.tel
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ringer_business.models.phone_number_assign_request import PhoneNumberAssignRequest

class TestPhoneNumberAssignRequest(unittest.TestCase):
    """PhoneNumberAssignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumberAssignRequest:
        """Test PhoneNumberAssignRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumberAssignRequest`
        """
        model = PhoneNumberAssignRequest()
        if include_optional:
            return PhoneNumberAssignRequest(
                id = 56,
                name = 'Main Sales Line',
                number = '+13035551234',
                site_id = 6,
                destination_code = 'menu:main_sales_ivr'
            )
        else:
            return PhoneNumberAssignRequest(
                name = 'Main Sales Line',
                number = '+13035551234',
                destination_code = 'menu:main_sales_ivr',
        )
        """

    def testPhoneNumberAssignRequest(self):
        """Test PhoneNumberAssignRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
