from enum import Enum


class INTEGRATION_KEYS(Enum):
    """
    INTEGRATION KEYS DESCRIPTION
    """

    # ODOO
    ODOO_URL = "ODOO_URL"
    ODOO_PASSWORD = "ODOO_PASSWORD"
    ODOO_USERNAME = "ODOO_USERNAME"
    ODOO_DB = "ODOO_DB"

    # MERCADO PAGO
    MP_ACCESS_TOKEN = "MP_ACCESS_TOKEN"

    # STRIPE

    # AFIP

    # OPEN AI
    OPEN_AI_API_KEY = "OPEN_AI_API_KEY"

    # INTERBANKING
    INTERBANKING_API_CLIENT = "INTERBANKING_API_CLIENT"
    INTERBANKING_API_KEY = "INTERBANKING_API_KEY"
    INTERBANKING_SERVICE_URL = "INTERBANKING_SERVICE_URL"


class DB_CONFIG_KEYS(Enum):
    DB_URL = "DB_URL"


class INTERNAL_KEYS(Enum):
    """
    INTERNAL KEYS DESCRIPTION
    """

    # TENANT SERVICE
    TENANT_SERVICE_URL = "TENANT_SERVICE_URL"
