from amsdal.models.core.class_property import *
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from typing import Any, ClassVar

class ClassObject(Model):
    __module_type__: ClassVar[ModuleType] = ...
    properties: dict[str, ClassProperty | None] | None = ...
    table_name: str | None = ...
    primary_key: list[str] | None = ...
    indexed: list[str] | None = ...
    unique: list[list[str]] | None = ...
    required: list[str] | None = ...
    meta_class: str | None = ...
    @classmethod
    def _non_empty_keys_properties(cls, value: Any) -> Any: ...
    @property
    def display_name(self) -> str:
        """
        Returns the display name of the object.

        Returns:
            str: The display name, which is the title of the object.
        """
