def full_version() -> str: ...

def set_verbose(verbosity: bool) -> None: ...

def validate_file(schema_filename: str, instance_filename: str) -> None: ...

def verify_file(filename: str) -> None: ...
