# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import typing
from .tls_details import TlsDetails
import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2


class TlsSummary(UniversalBaseModel):
    address: str
    tls_details: typing.Optional[TlsDetails] = pydantic.Field(alias="tlsDetails", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
