# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InvoiceStatusEnum(str, Enum):
    """
    InvoiceStatusEnum
    """

    """
    allowed enum values
    """
    DRAFT = 'draft'
    OPEN = 'open'
    VOID = 'void'
    PAID = 'paid'
    PAST_DUE = 'past_due'
    UNCOLLECTIBLE = 'uncollectible'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InvoiceStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


