# This file was generated by Nuitka

# Stubs included by default
from gllm_agents.memory.base import BaseMemory
from gllm_agents.executor.base import BaseExecutor
from gllm_agents.types import AgentProtocol
from gllm_agents.tools.base import BaseTool


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import asyncio
import typing
import abc
import a2a
import a2a.server
import a2a.server.agent_execution
import a2a.server.events
import a2a.server.events.event_queue
import a2a.server.tasks
import a2a.types
import a2a.utils
import json
import logging
import gllm_core
import gllm_core.event
import gllm_core.event.handler
import gllm_core.utils
import gllm_inference
import gllm_inference.lm_invoker
import gllm_inference.lm_invoker.langchain_lm_invoker
import gllm_inference.lm_invoker.lm_invoker
import gllm_inference.schema
import gllm_rag
import gllm_rag.preset
import gllm_rag.preset.initializer
import gllm_rag.preset.initializer.lm_invoker
import gllm_rag.preset.initializer.model_id
import langchain_core
import langchain_core.language_models
import httpx
import a2a.server.apps
import a2a.server.request_handlers
import starlette
import starlette.applications
import uuid
import langchain_core.messages
import langchain_core.tools
import langgraph
import langgraph.prebuilt
import contextlib
import time
import google
import google.adk
import google.adk.agents
import google.adk.agents.invocation_context
import google.adk.events
import google.adk.sessions
import google.adk.sessions.in_memory_session_service
import google.adk.sessions.state
import google.adk.tools
import google.adk.tools.base_tool
import google.adk.tools.langchain_tool
import google.adk.tools.mcp_tool
import google.adk.tools.mcp_tool.mcp_toolset
import google.genai
import google.genai.types
import langchain
import langchain.tools
import pydantic
import langchain_core.runnables
import langgraph.prebuilt.tool_executor
import langgraph.prebuilt.tool_node
import langchain.globals
import _frozen_importlib_external
import click
import uvicorn
import langchain_openai
import gllm_agents.examples.tools.weather_tool_langchain
import sys
import traceback
import gllm_agents.tools.BOSA_AUTOMATED_TOOLS
import nest_asyncio
import io
import subprocess
import threading
import fastapi
import fastapi.responses
import fastapi.staticfiles
import gllm_agents.sentry.setup_telemetry
import mcp
import mcp.server
import mcp.server.fastmcp
import random
import gllm_core.constants
import langchain.agents
import langchain.agents.tools
import langchain_core.agents
import langchain_core.callbacks
import types
import langchain_mcp_adapters
import langchain_mcp_adapters.client
import inspect
import bosa_core
import bosa_core.telemetry
import bosa_core.telemetry.opentelemetry
import bosa_core.telemetry.opentelemetry.instrument
import bosa_core.telemetry.opentelemetry.instrument.functions
import dotenv
import bosa_connectors
import bosa_connectors.connector
import enum
import re
import concurrent
import concurrent.futures
import a2a.client
import bosa_core.logger
import bosa_core.logger.regex_pii_logger_handler
import colorama