# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1235, 623)
        self.newProjectAction = QAction(MainWindow)
        self.newProjectAction.setObjectName(u"newProjectAction")
        self.openProjectAction = QAction(MainWindow)
        self.openProjectAction.setObjectName(u"openProjectAction")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.saveOtherProjectAction = QAction(MainWindow)
        self.saveOtherProjectAction.setObjectName(u"saveOtherProjectAction")
        self.saveOtherModelAction = QAction(MainWindow)
        self.saveOtherModelAction.setObjectName(u"saveOtherModelAction")
        self.saveOtherModelAction.setEnabled(True)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        self.ImportCoordinate = QAction(MainWindow)
        self.ImportCoordinate.setObjectName(u"ImportCoordinate")
        self.SelectPlateStruct = QAction(MainWindow)
        self.SelectPlateStruct.setObjectName(u"SelectPlateStruct")
        self.SelectPlateStruct.setEnabled(True)
        self.SelectProtec = QAction(MainWindow)
        self.SelectProtec.setObjectName(u"SelectProtec")
        self.SelectProtec.setEnabled(True)
        self.SelectMaterial = QAction(MainWindow)
        self.SelectMaterial.setObjectName(u"SelectMaterial")
        self.SelectMaterial.setEnabled(True)
        self.SelectFireHigh = QAction(MainWindow)
        self.SelectFireHigh.setObjectName(u"SelectFireHigh")
        self.SelectFireHigh.setEnabled(True)
        self.SelectInitiation = QAction(MainWindow)
        self.SelectInitiation.setObjectName(u"SelectInitiation")
        self.SelectInitiation.setEnabled(True)
        self.CalculationControl = QAction(MainWindow)
        self.CalculationControl.setObjectName(u"CalculationControl")
        self.EnvelopeAnalysis = QAction(MainWindow)
        self.EnvelopeAnalysis.setObjectName(u"EnvelopeAnalysis")
        self.Runing = QAction(MainWindow)
        self.Runing.setObjectName(u"Runing")
        self.action_LS_Prepost = QAction(MainWindow)
        self.action_LS_Prepost.setObjectName(u"action_LS_Prepost")
        self.action_20 = QAction(MainWindow)
        self.action_20.setObjectName(u"action_20")
        self.action_21 = QAction(MainWindow)
        self.action_21.setObjectName(u"action_21")
        self.action_22 = QAction(MainWindow)
        self.action_22.setObjectName(u"action_22")
        self.action_23 = QAction(MainWindow)
        self.action_23.setObjectName(u"action_23")
        self.action_24 = QAction(MainWindow)
        self.action_24.setObjectName(u"action_24")
        self.action_26 = QAction(MainWindow)
        self.action_26.setObjectName(u"action_26")
        self.action_27 = QAction(MainWindow)
        self.action_27.setObjectName(u"action_27")
        self.action_28 = QAction(MainWindow)
        self.action_28.setObjectName(u"action_28")
        self.action_29 = QAction(MainWindow)
        self.action_29.setObjectName(u"action_29")
        self.action_32 = QAction(MainWindow)
        self.action_32.setObjectName(u"action_32")
        self.action_33 = QAction(MainWindow)
        self.action_33.setObjectName(u"action_33")
        self.action_34 = QAction(MainWindow)
        self.action_34.setObjectName(u"action_34")
        self.action_38 = QAction(MainWindow)
        self.action_38.setObjectName(u"action_38")
        self.action_38.setEnabled(True)
        self.action_40 = QAction(MainWindow)
        self.action_40.setObjectName(u"action_40")
        self.action_40.setEnabled(True)
        self.action_41 = QAction(MainWindow)
        self.action_41.setObjectName(u"action_41")
        self.action_42 = QAction(MainWindow)
        self.action_42.setObjectName(u"action_42")
        self.action_43 = QAction(MainWindow)
        self.action_43.setObjectName(u"action_43")
        self.action_45 = QAction(MainWindow)
        self.action_45.setObjectName(u"action_45")
        self.action_46 = QAction(MainWindow)
        self.action_46.setObjectName(u"action_46")
        self.action_47 = QAction(MainWindow)
        self.action_47.setObjectName(u"action_47")
        self.action_update_log = QAction(MainWindow)
        self.action_update_log.setObjectName(u"action_update_log")
        self.action_50 = QAction(MainWindow)
        self.action_50.setObjectName(u"action_50")
        self.action_51 = QAction(MainWindow)
        self.action_51.setObjectName(u"action_51")
        self.action_52 = QAction(MainWindow)
        self.action_52.setObjectName(u"action_52")
        self.action_53 = QAction(MainWindow)
        self.action_53.setObjectName(u"action_53")
        self.action_56 = QAction(MainWindow)
        self.action_56.setObjectName(u"action_56")
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        self.SelectModel = QAction(MainWindow)
        self.SelectModel.setObjectName(u"SelectModel")
        self.action_dis = QAction(MainWindow)
        self.action_dis.setObjectName(u"action_dis")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_moxinxianshi = QAction(MainWindow)
        self.action_moxinxianshi.setObjectName(u"action_moxinxianshi")
        self.action_Prepost = QAction(MainWindow)
        self.action_Prepost.setObjectName(u"action_Prepost")
        self.action_results = QAction(MainWindow)
        self.action_results.setObjectName(u"action_results")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_6 = QAction(MainWindow)
        self.action_6.setObjectName(u"action_6")
        self.action_7 = QAction(MainWindow)
        self.action_7.setObjectName(u"action_7")
        self.action_9 = QAction(MainWindow)
        self.action_9.setObjectName(u"action_9")
        self.action_10 = QAction(MainWindow)
        self.action_10.setObjectName(u"action_10")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.stackedWidget_left = QStackedWidget(self.frame)
        self.stackedWidget_left.setObjectName(u"stackedWidget_left")
        self.stackedWidget_left.setMaximumSize(QSize(16777215, 16777215))
        self.stackedWidget_left.setFrameShape(QFrame.Panel)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayout_2 = QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.stackedWidget_left.addWidget(self.page_2)

        self.horizontalLayout.addWidget(self.stackedWidget_left)

        self.stackedWidget_right = QStackedWidget(self.frame)
        self.stackedWidget_right.setObjectName(u"stackedWidget_right")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.horizontalLayout_3 = QHBoxLayout(self.page)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget_right.addWidget(self.page)

        self.horizontalLayout.addWidget(self.stackedWidget_right)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)

        self.verticalLayout.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1235, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        self.menu_6 = QMenu(self.menubar)
        self.menu_6.setObjectName(u"menu_6")
        self.menu_7 = QMenu(self.menubar)
        self.menu_7.setObjectName(u"menu_7")
        self.menu_8 = QMenu(self.menubar)
        self.menu_8.setObjectName(u"menu_8")
        self.menu_10 = QMenu(self.menu_8)
        self.menu_10.setObjectName(u"menu_10")
        self.menu_9 = QMenu(self.menubar)
        self.menu_9.setObjectName(u"menu_9")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QToolBar(MainWindow)
        self.toolBar_2.setObjectName(u"toolBar_2")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.toolBar_3 = QToolBar(MainWindow)
        self.toolBar_3.setObjectName(u"toolBar_3")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QToolBar(MainWindow)
        self.toolBar_4.setObjectName(u"toolBar_4")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_4)
        MainWindow.insertToolBarBreak(self.toolBar_4)
        self.toolBar_5 = QToolBar(MainWindow)
        self.toolBar_5.setObjectName(u"toolBar_5")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_5)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_9.menuAction())
        self.menu.addAction(self.newProjectAction)
        self.menu.addAction(self.openProjectAction)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.saveOtherProjectAction)
        self.menu.addAction(self.saveOtherModelAction)
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.ImportCoordinate)
        self.menu_2.addAction(self.SelectModel)
        self.menu_2.addAction(self.SelectPlateStruct)
        self.menu_2.addAction(self.SelectProtec)
        self.menu_2.addAction(self.SelectMaterial)
        self.menu_2.addAction(self.SelectFireHigh)
        self.menu_2.addAction(self.SelectInitiation)
        self.menu_3.addAction(self.CalculationControl)
        self.menu_3.addAction(self.EnvelopeAnalysis)
        self.menu_3.addAction(self.Runing)
        self.menu_3.addAction(self.action_Prepost)
        self.menu_4.addAction(self.action_21)
        self.menu_4.addAction(self.action_23)
        self.menu_4.addAction(self.action_24)
        self.menu_4.addAction(self.action_moxinxianshi)
        self.menu_4.addAction(self.action_28)
        self.menu_4.addAction(self.action_22)
        self.menu_4.addAction(self.action_29)
        self.menu_4.addAction(self.action_26)
        self.menu_4.addAction(self.action_27)
        self.menu_5.addAction(self.action_32)
        self.menu_5.addAction(self.action_33)
        self.menu_5.addAction(self.action_52)
        self.menu_5.addAction(self.action_53)
        self.menu_6.addAction(self.action_38)
        self.menu_6.addAction(self.action_results)
        self.menu_7.addAction(self.action_40)
        self.menu_7.addAction(self.action_42)
        self.menu_7.addAction(self.action_43)
        self.menu_7.addAction(self.action_7)
        self.menu_7.addAction(self.action_9)
        self.menu_7.addAction(self.action_45)
        self.menu_7.addAction(self.action_56)
        self.menu_8.addAction(self.action_46)
        self.menu_8.addAction(self.action_47)
        self.menu_8.addAction(self.menu_10.menuAction())
        self.menu_8.addAction(self.action_10)
        self.menu_10.addAction(self.action)
        self.menu_10.addAction(self.action_2)
        self.menu_10.addAction(self.action_4)
        self.menu_9.addAction(self.action_update_log)
        self.menu_9.addAction(self.action_50)
        self.menu_9.addAction(self.action_about)
        self.toolBar.addAction(self.newProjectAction)
        self.toolBar.addAction(self.action_3)
        self.toolBar.addAction(self.saveOtherProjectAction)
        self.toolBar.addAction(self.saveOtherModelAction)
        self.toolBar.addAction(self.action_exit)
        self.toolBar_2.addAction(self.ImportCoordinate)
        self.toolBar_2.addAction(self.SelectModel)
        self.toolBar_2.addAction(self.SelectPlateStruct)
        self.toolBar_2.addAction(self.SelectProtec)
        self.toolBar_2.addAction(self.SelectMaterial)
        self.toolBar_2.addAction(self.SelectFireHigh)
        self.toolBar_2.addAction(self.SelectInitiation)
        self.toolBar_3.addAction(self.CalculationControl)
        self.toolBar_3.addAction(self.Runing)
        self.toolBar_3.addAction(self.action_Prepost)
        self.toolBar_4.addAction(self.action_moxinxianshi)
        self.toolBar_4.addAction(self.action_28)
        self.toolBar_4.addAction(self.action_23)
        self.toolBar_4.addAction(self.action_24)
        self.toolBar_4.addAction(self.action_21)
        self.toolBar_4.addAction(self.action_22)
        self.toolBar_4.addAction(self.action_29)
        self.toolBar_4.addAction(self.action_26)
        self.toolBar_4.addAction(self.action_27)
        self.toolBar_5.addAction(self.EnvelopeAnalysis)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.newProjectAction.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u7ed3\u6784\u6811", None))
        self.openProjectAction.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u9879\u76ee", None))
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u9879\u76ee", None))
        self.saveOtherProjectAction.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4eff\u771f\u6a21\u677f", None))
#if QT_CONFIG(tooltip)
        self.saveOtherProjectAction.setToolTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4eff\u771f\u6a21\u677f", None))
#endif // QT_CONFIG(tooltip)
        self.saveOtherModelAction.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u5230\u4eff\u771f\u6a21\u677f\u5e93", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.ImportCoordinate.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u5750\u6807\u6587\u4ef6", None))
        self.SelectPlateStruct.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u9776\u677f\u7ed3\u6784", None))
        self.SelectProtec.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u4fdd\u62a4\u7f69\u7ed3\u6784\uff08\u9884\u7559\u63a5\u53e3\uff09", None))
        self.SelectMaterial.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6750\u6599", None))
        self.SelectFireHigh.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u70b8\u9ad8", None))
        self.SelectInitiation.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u8d77\u7206\u70b9", None))
        self.CalculationControl.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u63a7\u5236", None))
        self.EnvelopeAnalysis.setText(QCoreApplication.translate("MainWindow", u"\u5305\u7edc\u5206\u6790", None))
        self.Runing.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c", None))
        self.action_LS_Prepost.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210\u5de5\u51b5", None))
#if QT_CONFIG(tooltip)
        self.action_LS_Prepost.setToolTip(QCoreApplication.translate("MainWindow", u"\u751f\u6210\u5de5\u51b5", None))
#endif // QT_CONFIG(tooltip)
        self.action_20.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u62a5\u544a", None))
        self.action_21.setText(QCoreApplication.translate("MainWindow", u"\u4fb5\u5f7b\u5206\u79bb\u6027\u80fd", None))
#if QT_CONFIG(tooltip)
        self.action_21.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fb5\u5f7b\u5206\u79bb\u6027\u80fd", None))
#endif // QT_CONFIG(tooltip)
        self.action_22.setText(QCoreApplication.translate("MainWindow", u"\u4fb5\u5f7b\u7387\u66f2\u7ebf", None))
#if QT_CONFIG(tooltip)
        self.action_22.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fb5\u5f7b\u7387\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.action_23.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.action_23.setToolTip(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6", None))
#endif // QT_CONFIG(tooltip)
        self.action_24.setText(QCoreApplication.translate("MainWindow", u"\u538b\u529b", None))
#if QT_CONFIG(tooltip)
        self.action_24.setToolTip(QCoreApplication.translate("MainWindow", u"\u538b\u529b", None))
#endif // QT_CONFIG(tooltip)
        self.action_26.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u5ea6\u66f2\u7ebf", None))
#if QT_CONFIG(tooltip)
        self.action_26.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bc6\u5ea6\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.action_27.setText(QCoreApplication.translate("MainWindow", u"\u80fd\u91cf\u66f2\u7ebf", None))
#if QT_CONFIG(tooltip)
        self.action_27.setToolTip(QCoreApplication.translate("MainWindow", u"\u80fd\u91cf\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.action_28.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u683c\u5212\u5206\u793a\u610f\u56fe", None))
#if QT_CONFIG(tooltip)
        self.action_28.setToolTip(QCoreApplication.translate("MainWindow", u"\u7f51\u683c\u5212\u5206\u793a\u610f\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_29.setText(QCoreApplication.translate("MainWindow", u"\u5c04\u6d41\u5934\u90e8\u5408\u901f\u5ea6\u66f2\u7ebf", None))
#if QT_CONFIG(tooltip)
        self.action_29.setToolTip(QCoreApplication.translate("MainWindow", u"\u5c04\u6d41\u5934\u90e8\u5408\u901f\u5ea6\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.action_32.setText(QCoreApplication.translate("MainWindow", u"Z\u6b63\u5411\u89c6\u56fe", None))
#if QT_CONFIG(tooltip)
        self.action_32.setToolTip(QCoreApplication.translate("MainWindow", u"Z\u6b63\u5411\u89c6\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_33.setText(QCoreApplication.translate("MainWindow", u"Z\u8d1f\u5411\u89c6\u56fe", None))
#if QT_CONFIG(tooltip)
        self.action_33.setToolTip(QCoreApplication.translate("MainWindow", u"Z\u8d1f\u5411\u89c6\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_34.setText(QCoreApplication.translate("MainWindow", u"\u590d\u4f4d\u754c\u9762", None))
        self.action_38.setText(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u7ed3\u6784", None))
        self.action_40.setText(QCoreApplication.translate("MainWindow", u"\u6750\u6599\u5e93", None))
        self.action_41.setText(QCoreApplication.translate("MainWindow", u"\u5207\u5272\u7d22\u578b\u9762\u5e93", None))
        self.action_42.setText(QCoreApplication.translate("MainWindow", u"\u9776\u677f\u7ed3\u6784\u5e93", None))
        self.action_43.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u62a4\u7f69\u7ed3\u6784\u5e93(\u5f85\u5f00\u53d1)", None))
        self.action_45.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u6a21\u677f\u5e93", None))
        self.action_46.setText(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u73af\u5883", None))
        self.action_47.setText(QCoreApplication.translate("MainWindow", u"\u5e76\u884c\u7a97\u53e3\u8fd0\u7b97", None))
        self.action_update_log.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u66f4\u65b0\u65e5\u5fd7", None))
        self.action_50.setText(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u4f7f\u7528\u8bf4\u660e", None))
        self.action_51.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u7248\u672c\u540d\u79f0", None))
        self.action_52.setText(QCoreApplication.translate("MainWindow", u"\u5c45\u4e2d\u89c6\u56fe", None))
        self.action_53.setText(QCoreApplication.translate("MainWindow", u"\u590d\u4f4d\u89c6\u56fe", None))
        self.action_56.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u62a5\u544a\u5e93", None))
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.SelectModel.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6a21\u677f", None))
        self.action_dis.setText(QCoreApplication.translate("MainWindow", u"\u4f4d\u79fb\u66f2\u7ebf", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u666e\u901a\u7528\u6237", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u7ea7\u7528\u6237", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u7ba1\u7406\u5458", None))
        self.action_moxinxianshi.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u793a\u610f\u56fe", None))
#if QT_CONFIG(tooltip)
        self.action_moxinxianshi.setToolTip(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u793a\u610f\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_Prepost.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8LS-Prepost", None))
#if QT_CONFIG(tooltip)
        self.action_Prepost.setToolTip(QCoreApplication.translate("MainWindow", u"\u542f\u52a8LS-Prepost", None))
#endif // QT_CONFIG(tooltip)
        self.action_results.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u6570\u636e\u5e93", None))
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u62a5\u544a", None))
        self.action_6.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u89c6\u9891", None))
        self.action_7.setText(QCoreApplication.translate("MainWindow", u"\u6a61\u80f6\u62a4\u5957\u7ed3\u6784\u5e93(\u5f85\u5f00\u53d1)", None))
        self.action_9.setText(QCoreApplication.translate("MainWindow", u"\u7d27\u56fa\u4ef6\u7ed3\u6784\u5e93(\u5f85\u5f00\u53d1)", None))
        self.action_10.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u5bc6\u7801", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5efa\u6a21", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u5206\u6790", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u51fa", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_6.setTitle(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u6570\u636e\u5e93", None))
        self.menu_7.setTitle(QCoreApplication.translate("MainWindow", u"\u6458\u8981", None))
        self.menu_8.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menu_10.setTitle(QCoreApplication.translate("MainWindow", u"\u5207\u6362\u7528\u6237", None))
        self.menu_9.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.toolBar_2.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_2", None))
        self.toolBar_3.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_3", None))
        self.toolBar_4.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_4", None))
        self.toolBar_5.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_5", None))
    # retranslateUi
