// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xla/shape_util.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xla_2fshape_5futil_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xla_2fshape_5futil_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xla_2fshape_5futil_2eproto PROTOBUF_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct PROTOBUF_EXPORT TableStruct_xla_2fshape_5futil_2eproto {
  static const uint32_t offsets[];
};
PROTOBUF_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xla_2fshape_5futil_2eproto;
namespace xla {
class ShapeIndexProto;
struct ShapeIndexProtoDefaultTypeInternal;
PROTOBUF_EXPORT extern ShapeIndexProtoDefaultTypeInternal _ShapeIndexProto_default_instance_;
}  // namespace xla
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_EXPORT ::xla::ShapeIndexProto* Arena::CreateMaybeMessage<::xla::ShapeIndexProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xla {

// ===================================================================

class PROTOBUF_EXPORT ShapeIndexProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xla.ShapeIndexProto) */ {
 public:
  inline ShapeIndexProto() : ShapeIndexProto(nullptr) {}
  ~ShapeIndexProto() override;
  explicit PROTOBUF_CONSTEXPR ShapeIndexProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShapeIndexProto(const ShapeIndexProto& from);
  ShapeIndexProto(ShapeIndexProto&& from) noexcept
    : ShapeIndexProto() {
    *this = ::std::move(from);
  }

  inline ShapeIndexProto& operator=(const ShapeIndexProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShapeIndexProto& operator=(ShapeIndexProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShapeIndexProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShapeIndexProto* internal_default_instance() {
    return reinterpret_cast<const ShapeIndexProto*>(
               &_ShapeIndexProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ShapeIndexProto& a, ShapeIndexProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ShapeIndexProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShapeIndexProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShapeIndexProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShapeIndexProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShapeIndexProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShapeIndexProto& from) {
    ShapeIndexProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShapeIndexProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xla.ShapeIndexProto";
  }
  protected:
  explicit ShapeIndexProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexesFieldNumber = 1,
  };
  // repeated int64 indexes = 1;
  int indexes_size() const;
  private:
  int _internal_indexes_size() const;
  public:
  void clear_indexes();
  private:
  int64_t _internal_indexes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_indexes() const;
  void _internal_add_indexes(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_indexes();
  public:
  int64_t indexes(int index) const;
  void set_indexes(int index, int64_t value);
  void add_indexes(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      indexes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_indexes();

  // @@protoc_insertion_point(class_scope:xla.ShapeIndexProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > indexes_;
    mutable std::atomic<int> _indexes_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xla_2fshape_5futil_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ShapeIndexProto

// repeated int64 indexes = 1;
inline int ShapeIndexProto::_internal_indexes_size() const {
  return _impl_.indexes_.size();
}
inline int ShapeIndexProto::indexes_size() const {
  return _internal_indexes_size();
}
inline void ShapeIndexProto::clear_indexes() {
  _impl_.indexes_.Clear();
}
inline int64_t ShapeIndexProto::_internal_indexes(int index) const {
  return _impl_.indexes_.Get(index);
}
inline int64_t ShapeIndexProto::indexes(int index) const {
  // @@protoc_insertion_point(field_get:xla.ShapeIndexProto.indexes)
  return _internal_indexes(index);
}
inline void ShapeIndexProto::set_indexes(int index, int64_t value) {
  _impl_.indexes_.Set(index, value);
  // @@protoc_insertion_point(field_set:xla.ShapeIndexProto.indexes)
}
inline void ShapeIndexProto::_internal_add_indexes(int64_t value) {
  _impl_.indexes_.Add(value);
}
inline void ShapeIndexProto::add_indexes(int64_t value) {
  _internal_add_indexes(value);
  // @@protoc_insertion_point(field_add:xla.ShapeIndexProto.indexes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
ShapeIndexProto::_internal_indexes() const {
  return _impl_.indexes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
ShapeIndexProto::indexes() const {
  // @@protoc_insertion_point(field_list:xla.ShapeIndexProto.indexes)
  return _internal_indexes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
ShapeIndexProto::_internal_mutable_indexes() {
  return &_impl_.indexes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
ShapeIndexProto::mutable_indexes() {
  // @@protoc_insertion_point(field_mutable_list:xla.ShapeIndexProto.indexes)
  return _internal_mutable_indexes();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace xla

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xla_2fshape_5futil_2eproto
